version: "3.8"
services:
  app:
    build:
      args:
        user: dion
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: tokokopi
    container_name: tokokopi-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tokokopi

  nginx:
    image: nginx:1.17-alpine
    container_name: tokokopi-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - tokokopi

networks:
  tokokopi:
    driver: bridge
